-- 코드를 입력하세요
SELECT R.REST_ID, R.REST_NAME, R.FOOD_TYPE, R.FAVORITES, R.ADDRESS, ROUND(AVG(REVIEW.REVIEW_SCORE), 2) AS AVERAGE
FROM REST_INFO AS R
JOIN REST_REVIEW AS REVIEW
ON R.REST_ID = REVIEW.REST_ID
WHERE R.ADDRESS LIKE "서울%"
GROUP BY R.REST_ID
ORDER BY AVERAGE DESC, R.FAVORITES DESC