SELECT CHILD.ITEM_ID, CHILD.ITEM_NAME, CHILD.RARITY
FROM ITEM_INFO AS CHILD
JOIN ITEM_TREE AS TREE ON TREE.ITEM_ID = CHILD.ITEM_ID
JOIN ITEM_INFO AS PARENT ON TREE.PARENT_ITEM_ID = PARENT.ITEM_ID
WHERE PARENT.RARITY = 'RARE' AND TREE.PARENT_ITEM_ID IS NOT NULL
ORDER BY ITEM_ID DESC